/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative */

#ifndef _Included_info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
#define _Included_info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeCreate
 * Signature: (Linfo/kghost/android_hole/vpn/dataplane/TunnelDataPlaneCallbacks;Landroid/net/ConnectivityManager;)J
 */
JNIEXPORT jlong JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeCreate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeStart
 * Signature: (JII[B)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeStart
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeMigrateTun
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeMigrateTun
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeAddEndpoint
 * Signature: (J[BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeAddEndpoint
  (JNIEnv *, jclass, jlong, jbyteArray, jstring);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeRemoveEndpoint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeRemoveEndpoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeStartEndpoint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeStartEndpoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeStopEndpoint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeStopEndpoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeGetTrafficStats
 * Signature: (JJLinfo/kghost/android_hole/vpn/dataplane/JniTunnelDataPlaneNative/TrafficStats;)Z
 */
JNIEXPORT jboolean JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeGetTrafficStats
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     info_kghost_android_hole_vpn_dataplane_JniTunnelDataPlaneNative
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_kghost_android_1hole_vpn_dataplane_JniTunnelDataPlaneNative_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
